alphagov/tdt-documentation

source/index.html.md.erb
Testing ability to raise PR.
Remove some filler text.
None.
=> Remove 'Hello world!'

source/support/index.html.md.erb
Changed config parameters to make the page appear as expired.
This is to test what happens. What does the banner on the page look like? Do any alerts get pushed to Slack?
Relevant documentation: https://alphagov.github.io/tech-docs-manual/#last-reviewed-on-and-review-in
@bravegrape
=> Test what happens when page has expired

source/architecture/multipage.md
The tech doc tool can handle both single and multipage documentation. 
Create multipage documentation section
=> Add multipage

source/preview/temp_version.md
=> Create "Push temp doc site to GOV.UK PaaS" section

config/tech-docs.yml, source/api_ref.html.md.erb, source/collapsible_nav.html.md.erb, source/create_new_project.html.md.erb, source/functionality/collapsible_nav.md, source/index.html.md.erb, source/install_macs.html.md.erb, source/introduction/introduction.md, source/multipage.html.md.erb, source/search.html.md.erb, source/single_page.html.md.erb, source/support/index.html.md.erb
Staging a multipage structure for review with Tijmen.
Implement basic multipage structure.
Check it works.
=> multipage structure

source/support/index.html.md.erb
Add support information
Add support information
=> Expand support page

source/architecture/multipage.md
Add example folder structure diagrams to help users build single and multipage docs.
Added folder structure example diagrams for:
- single page
- basic multipage
- nested multipage
=> Add diagrams

source/support/index.html.md.erb, source/support/support.md
Moved contact info into one markdown file to simplify structure
=> Amend support section

source/publish/push-repo.md
Refine rough content into numbered instructions
=> Make into instructions

source/support/support.md
=> Fix bugged table

source/support.html.md.erb, source/support/index.html.md.erb
Current docs left hand nav has issues in support section
Move support.html.md.erb to source folder
=> Move support index file

source/publish.html.md.erb, source/publish/ci.md, source/publish/push-repo.md
Fix left hand nav issues in publish section
Move ci content to push-repo.md and change .html.md.erb files to reflect this
=> Update publish section

source/introduction/introduction.md
We must specify that the tool and the documentation for the tool are intended only for internal use within GDS and the government community.
Added:
- Who should use the tool?
- Who is this documentation website for?
=> Add content on who this is for

source/content.html.md.erb, source/content_example/content.md
Content examples are useful.
Add content examples.
=> add content examples

source/content_example/content.md
Open links in new internet browser tab. This is useful for external links.
Added in html with target=blank element.
=> Open links in new browser tab

source/publish/push_repo.md
Adds example deployment to temporary PaaS site.
=> Adds example deployment content

source/publish/push_repo.md
Reverts alphagov/tdt-documentation#53
=> Revert "Adds example deployment content"

source/manage_project/create_new_project.md
=> Tweak new project creation instructions

README.md
We need to update the repository README to provide useful information for making changes to the documentation content.
The proposed changes are based on bringing content in line with the README for the tech-docs-template repo: https://github.com/alphagov/tech-docs-template/blob/master/README.md
=> Update README to contain sections relevant to making changes

source/architecture/multipage.md, source/architecture/single_page.md
Add in some missing links.
Add in some missing links.
=> add in two links to content examples and search sections

source/getting_started/install_macs.md
Previously you would send an email to sd-community to get admin rights on your laptop. Now you raise a ticket on GDS Web Help Desk.
Update content to reflect new process.
=> Update admin rights process

source/publish/push_repo.md
There is no single list of all content that uses the TDT
Add in table summarising all current published content that uses the TDT
=> Add in table of published docs

README.md
links were broken
fix links in readme
new links should work
=> fix installation links

source/review_project/temp_version/index.html.md.erb
Users reported that the guidance was confusing and hard to follow
Some out-of-date info and unnecessary steps removed
The steps on this page
=> Remove some steps in guidance

config/tech-docs.yml
The top-left link in the header is an empty link.
Add a service link to the config.yml file.
Please check it works ok.
=> Add service link to config

source/accessibility/index.html.md.erb
Adds table row header clause and links to criteria.
Adds table row header clause and links to criteria.
=> Adds table row header clause and links to criteria

source/accessibility/index.html.md.erb
We're updated the Tech Docs Template to v2.2.2, which fixes the accessibility issues mentioned in the statement.
Remove list of accessibility issues in both accessibility sections (the docs, and the template itself).
Please check everything looks ok.
=> Update accessibility statement

source/partials/_links.erb, source/support/index.html.md.erb
Update typos on the Support page, and fix links that are currently the wrong way round.
=> Fix typos on Support page

source/index.html.md.erb
Update the Tech Docs Template documentation intro to fix some style issues, condense it and improve user journeys.
=> Fix intro style and condense

source/configure_project/global_configuration/index.html.md.erb
Adds in documentation about how to build a site using relative links.
=> adds in documentation how to build a site using relative links
