source/index.html.md.erb

Adds a more descriptive note about the TDT; main reason for this PR is to test that Travis CI is functioning as intended

Adds more descriptive note about TDT

---

config/tech-docs.yml
source/support/index.html.md.erb

* set `owner_slack:` to the github alerts channel to test out page expiry
* set `last_reviewed_on: 2018-11-27` and `review_in: 1 day` to see what this looks like in the front end
@bravegrape @bahmady

Added Slack ownership to test page expiry

---

config/tech-docs.yml

Cannot show crown logo without a `.gov.uk` url.
Add flag to config.yml and set to false

Set GOV.UK crown logo to false

---

source/preview/temp_version.md

Run `bundle exec middleman server` to preview your content from your local machine.
Run `bundle exec middleman server` to preview your content from your local machine.

Bundle exec middleman server

---

config.rb
source/configuration-options.html.md.erb
source/frontmatter.html.md.erb

This includes two pieces of documentation from the gem directly into
this site:
https://github.com/alphagov/tech-docs-gem/blob/master/docs/configuration.md
https://github.com/alphagov/tech-docs-gem/blob/master/docs/frontmatter.md
The advantage of pulling in the markdown files like this is that developers can update the code and docs in a single PR, which makes it less likely the docs are forgotten.
This is part of the now deprecated https://github.com/alphagov/tech-docs-manual.

Include site config & frontmatter docs

---

source/middleman.html.md.erb

We need some information about redirects, but also about running locally and building. We shouldn't necessarily describe this in detail ourselves since Middleman also has good documentation about this, but we haven't decided this for sure—this could always be iterated on in future
Adds a new section pointing to relevant Middleman documentation that isn't already covered in existing documentation / is unlikely to ever be 
Might be worth removing the 'Frontmatter' section or changing it if we add this section, since Middleman has a lot of guidance about that and I'm not sure how much of it is tool-specific: https://middlemanapp.com/basics/frontmatter/

Adds a section pointing to important Middleman docs 

---

source/publish/push-repo.md

We need a section about deploying sites (static ones which have been built with the GDS TDT)
Adds some instructions on deploying and points to PaaS docs re. CI
Jon this might be a bit of a troublesome one because of some people wanting to use GH Pages. I've tried to anticipate this but it's your call how you want to word this

Deployment instructions

---

source/api_ref.html.md.erb
source/architecture/multipage.md
source/architecture/single_page.md
source/collapsible_nav.html.md.erb
source/configuration-options.html.md.erb
source/create_new_project.html.md.erb
source/frontmatter.html.md.erb
source/functionality/update_gem.md
source/index.html.md.erb
source/install_macs.html.md.erb
source/middleman.html.md.erb
source/multipage.html.md.erb
source/publish.html.md.erb
source/publish/push_repo.md
source/publish_docs.html.md.erb
source/search.html.md.erb
source/single_page.html.md.erb
source/support_info.html.md.erb
source/update_gem.html.md.erb
source/warning.html.md.erb

The left hand nav in the support and publish sections were not displaying correctly. This was driven by the relevant *.html.md.erb files having the same name as the folders that the .html.md.erb files use partials to refer to. For example, you cannot have a support.html.md.erb file that contains the partial `<%= partial 'support/contact_us' %>`.
Corrected this error and added guidance into the single and multipage sections to this effect. Also added in content on updating ruby gems.
- Correct left hand nav by renaming subfolders. 
- Add in guidance on .html.md.erb filenames being different to subfolders they refer to. 
- Add in guidance to update all ruby gems in repo.

Left hand nav and update ruby gems

---

source/introduction/introduction.md

We should remove FAQs from the TDT
Changes FAQ format to statement format in introduction, renames title to 'GDS technical documentation tool', removes duplicate

Removes FAQ format from intro

---

source/content_example/content.md

You can also write tables in HTML, especially if you want to add extra formatting that is not covered by markdown.
Add HTML tables to content examples section.

add html tables to content examples section

---

source/getting_started/install_macs.md

See commits for details:
- Make clear that requesting admin rights is something that only GDS people can do 
- Recommend installing Ruby 2.6.1 so that we don't need to install bundler
- Don't separately install `govuk_tech_docs` gem 

Tweak installations instructions

---

README.md
config/tech-docs.yml
source/index.html.md.erb
source/introduction/introduction.md
source/middleman.html.md.erb
source/publish/push_repo.md

In other repos, this project is named "Tech Docs Template". We should be consistent, so I suggest we either rename this particular repo, or rename it in the other repos:
- https://github.com/alphagov/tech-docs-template
- https://github.com/alphagov/tech-docs-gem
- https://github.com/alphagov/tech-docs-monitor
I may have missed a discussion about the branding of the project, so putting this up for discussion.

[DISCUSS] Rename to "Tech Docs Template"

---

source/getting_started/install_macs.md

This is to review the list of requirements for Macs.
The 'Prerequisites' page should say what the prerequisites enable the user to do. 
Some requirements listed are redundant, while others don't necessarily apply for all tasks a user might carry out. One could even argue that you need none of the stuff in the list to contribute to docs if you use the GitHub UI.
The PR proposes removing 2 redundant requirements.
First, remove:
"You must also have a [GitHub account](https://github.com/) [external link] with access to alphagov at `https://github.com/alphagov/paas-tech-docs`."
The link does not make sense and there is no need for access to alphagov to use and contribute to the TDT. Also users don't even need a GitHub account if they just want to use the TDT.
Second, remove the requirement for …

Review prerequisites

---

source/publish/push_repo.md

Adding basic auth to temporary documentation sites is useful to restrict access e.g. during recruitment.
Adds content on adding basic auth to your documentation site.

Add basic authentication

---

source/getting_started/install_macs.md
source/introduction/introduction.md
source/middleman.html.md.erb
source/publish/push_repo.md

The [content design guidance on links](https://www.gov.uk/guidance/content-design/links) no longer requires `[external link]` labelling of linked text leading outside of the trusted `.gov.uk` domain.
This is great because these `[external link]` labels make the content look messy and unfinished, which is potentially damaging users' trust in the content.
It should still be obvious to the user when they've been sent to a different domain.
Remove `[external link]` labels.
The recognisably different branding on the external websites suggests there is no reason documentation users will be confused and believe they're still on the Tech Docs Template documentation website.

Remove [external link] labels

---

README.md

There is some left over markup from when I solved a merge conflict.
The PR removes the left over markup.

Remove merge conflict markup

---

source/page-expiry.html.md.erb

Some content is being copied over from `alphagov/tech-docs-gem/docs`, for example the content for the 'Configuration' and 'Frontmatter' sections.
The content about [page review and expiry](https://github.com/alphagov/tech-docs-gem/blob/master/docs/page-expiry.md) which is also found in `alphagov/tech-docs-gem/docs` is not being copied over.
Bring the content about page expiry to the TDT docs into a separate page.
It makes sense to have this as a separate page because the content of the page brings together both frontmatter and global config settings and discusses the feature asa whole.

Add missing documentation about page expiry and review

---

source/architecture/single_page.md

While using this documentation I noticed that the markdown on one of the links is slightly broken, so here's a patch for it. 🤷‍♂️

Fix link markdown

---

source/functionality/warning.md

The warning text component has been integrated into the govuk-tech-docs gem so the extensive HTML is no longer needed.
Replace previous required HTML with simpler implemented text.

Update warning text

---

source/add_an_openapi_specification.html.md.erb
source/api_ref.html.md.erb
source/functionality/add_an_openapi_specification.md

We recently used this template to document an API, and very nearly missed the useful feature which automatically generates good-looking documentation from an OpenAPI spec. It was hidden under the the term "API reference", which is not very explicit.
Change the menu item "API reference" to "Incorporate an OpenAPI spec", and change the associated page title too.
While we're here, add a link to the swagger.io `/about` page to help those who don't know what OpenAPI is.
a) agree/disagree that the existing menu item is a bit obscure
b) consider whether the replacement could be better worded

Rename "API Reference" to "Add an OpenAPI specification to your documentation"

---

config/tech-docs.yml

The links in the website header are not useful.
'Documentation' and 'Support' don't go anywhere.
'About' goes to a GDS Wiki page which users outside GDS cannot access.
Remove the links to 'Documentation' and 'About'.
Link 'Support' to the new 'Support' section.
Create new links to go to the template repo and the tehc docs gem repo on GitHub which are more useful.
See commit messages for more details.
Fixes #89 
Assess proposal for new header links and propose an alternative if appropriate.

Re-configure header links

---

source/amend_project/content/index.html.md.erb

We need to escape the ERB command to have it rendered as a command in the
code block example. Not escaping the ERB means the command is being
executed, which is not the point of this content.
ERB in code block examples gets executed rather than being displayes as is.
For example, the code block containing our Middleman helper method
Gets evaluated and displayed as HTML, which defeats the point of that piece of guidance:
Escape the ERB example using `<%%=` instead of `<%=` to avoid it being executed.
Renders as:
Check the code block example  contains ERB, not HTML.

Escape ERB to fix the code block example

---

config/tech-docs.yml
source/create_project/multipage/index.html.md.erb
source/create_project/single_page/index.html.md.erb

Changing the information architecture as part of https://github.com/alphagov/tdt-documentation/pull/97 meant that some links broke.
The scope of this PR is to redirect broken links so that links to the old pages don't return 404s, but take the user to the right place in the new information architecture.
I'm using the list @36degrees put together in issue https://github.com/alphagov/tdt-documentation/issues/105 to keep track of the work:
|From|To                           |Anchor Text| Redirected to |
|----|-----------------------------|-----------|----|
|https://tdt-documentation.london.cloudapps.digital/review_project/page-expiry/|https://tdt-documentation.london.cloudapps.digital/review_project/page-expiry/not-expired-page.png|           | Unlikely to be linked to | …

Set up redirects

---

source/publish_project/current/index.html.md.erb

GOV.UK Frontend documentation is now using the Tech Docs Template at http://frontend.design-system.service.gov.uk/
- Update the publications table with the GOV.UK Frontend link and repo
- Correct the table markdown
- Add proper links and make the link text accessible
- Fix ordering of the GDS publications so they're alphabetical
- Update review date
Please check if all ok.

Add GOV.UK Frontend docs to publications table

---

source/configure_project/frontmatter/index.html.md.erb

Document missing and new frontmatter options.
- Document existing 'description' frontmatter, used used by search engines (`<meta name="description">`) and when shared on social media (`<meta property="og:description">`)
- Document new `prevent_indexing` frontmatter, which will be introduced in in https://github.com/alphagov/tech-docs-gem/pull/192
You can verify how the `description` frontmatter is used [here](https://github.com/alphagov/tech-docs-gem/blob/d077820ab9dec2373fea4761c9f52d0e76cfc46a/lib/govuk_tech_docs/meta_tags.rb#L10-L11).
The ['prevent_indexing` option could previously be set as a site-wide option](https://tdt-documentation.london.cloudapps.digital/configure_project/global_configuration/#prevent-indexing) but https://github.com/alphagov/tech-docs-gem/pull/192 will make it …

Add missing frontmatter

---

source/configure_project/global_configuration/index.html.md.erb

This change makes it clearer that if you use the config setting to enable Google Analytics, you should follow the guidance on working with cookies in the Service Manual.
We should add something similar to documentation change in https://github.com/alphagov/tdt-documentation/pull/126 (which documents the proposed addition of a Google Tag Manager config setting https://github.com/alphagov/tech-docs-gem/pull/187).

Add link to service manual from Google Analytics config section

---

source/accessibility/index.html.md.erb

Updated the date for fixing the Tech Docs Template accessibility issues from “end of December 2020” to “end of March 2021”. As a result of resourcing pressures and re-prioritisation this year, it’s taking longer than we hoped to arrange developer and designer resources to fix the accessibility issues.

Update accessibility statement dates

---

source/accessibility/index.html.md.erb

This PR updates the "last reviewed" date in the accessibility statement to the merge date of the last pull request that changed the accessibility statement. We forgot to change the "last reviewed" date at that time.

Update accessibility statement review date to match PR #137

---

source/configure_project/structure_docs/index.html.md.erb

The current version misspells _Introduction_.

Fix typo in Tech Docs Template content

---

source/create_project/get_started/index.html.md.erb

A user found the Get Started content needed clarifying around the Ruby version to install.
Clarify that `x.x.x` is the Ruby version number.

Clarify Ruby version number and add example of Ruby version number

---

README.md

The [tech-docs-template repo README](https://github.com/alphagov/tech-docs-template) no longer has content that duplicates [the TDT documentation](https://tdt-documentation.london.cloudapps.digital/).
This PR does the same for the tdt-documentation repo.
Trello card: https://trello.com/c/m4JOepVJ/153-de-duplicate-tech-docs-repo-readmes

Remove tdt docs content from readme file 

---

source/write_docs/content/index.html.md.erb

This removes the requirement to add a `<div>` above and below tables. This was originally required because omitting them would break the table completely, but this no longer seems to be an issue. The spacing between the table and the surrounding content is now slightly reduced as a result, but this should be fixed with CSS in the tech docs gem, rather than with non-semantic content.
This commit also documents new accessibility guidance whereby tables with 3 or more columns need a row header, introduced in https://github.com/alphagov/tech-docs-gem/pull/214.
While I'm here, I've updated the markdown example to use padded cells for horizontal alignment, which is good practice if there is room to do so. I've also omitted the `|:---|` left-alignment instruction, since cells are left-aligned by …

Update table markdown guidance

---

source/accessibility/index.html.md.erb

There are some new accessibility issues with the Tech Docs Template, reported in a recent DAC audit arranged by the GovWifi team. 
The issues are the following.
- IOn page load, the main page heading in the content is automatically focused. Keyboard-only users expect the focus to be at the top of the page and then move through the navigation elements. Keyboard-only users may therefore miss the navigation elements which would be confusing. This fails [WCAG 2.1 success criterion 2.4.3 - Focus Order](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html).
- The navigation elements are not marked-up as hierarchical headings. As screen reader users rely on correct semantic mark-up to determine relationships within the page, this makes navigating a page using a screen reader more …

Update accessibility statement to say not fully compliant

---

config/tech-docs.yml

The link to the docs owners in the review boxes is incorrect because the Slack channel doesn't exist anymore. Updated to the correct Slack channel.

Update docs owner Slack channel

---

source/support/index.html.md.erb

We're introducing a new process for Tech Docs Template PRs.
Add a 'Contributions' section to the Support page that explains the new process. It borrows content from https://github.com/alphagov/tech-docs-gem/blob/master/CONTRIBUTING.md (and we'll update that page to link to this new content).
This has been 2i'd - just needs approval to merge.

Add contribution documentation

---

source/configure_project/global_configuration/index.html.md.erb

Add documentation on having a colon in a value in the `config/tech-docs.yml` file, and how you need to wrap the value in quotes.
Technical writer in HMRC needed guidance on this on 2021/10/19.

Add docs about colon

---

source/create_project/get_started/index.html.md.erb

Fixes https://github.com/alphagov/tdt-documentation/issues/182
The [Get started](https://tdt-documentation.london.cloudapps.digital/create_project/get_started/#install-node-js) page says users should install the most recent stable release of Ruby. But the TDT has only been tested up to 2.7.x, so users should install that instead.
As a result, we've seen people get errors when they try to install the TDT using later versions of Ruby.
This PR updates the install documentation.

Fix Ruby version in install docs

---

.github/workflows/deploy.yaml
README.md
source/configure_project/global_configuration/index.html.md.erb
source/partials/_links.erb
source/support/index.html.md.erb
source/write_docs/add_openapi_spec/index.html.md.erb

We're trying to phase out use of the word 'master' as the default default branch name, along with the rest of the software engineering community [[1]].
This PR updates the docs, as we're updating the template in PR alphagov/tech-docs-template#228, and adds a note about changing the default in a future release of the gem (see https://github.com/alphagov/tech-docs-gem/blob/d3a1545158c5f9c78caafcbbbd7ddd097fdeedcb/lib/govuk_tech_docs/contribution_banner.rb#L42).
We also need to update some links and the deploy script for this repo.
[1]: github.com/renaming

Rename default branch to 'main'

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
source/support/index.html.md.erb

Tech docs template is now managed by the working group, update references to CDDO technical writing team (which no longer exists).
Closes #189.

Replace references to CDDO technical writing group with tdt working group

---

source/publish_project/deploy/index.html.md.erb

GOV.UK PaaS is being decommissioned. Remove references to the service from our docs.

Remove references to PaaS
